default: &default
  adapter: postgresql
  pool: 20
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: nommit-development

test:
  <<: *default
  database: nommit-test

production:
  <<: *default
  database: production
